"""Generate ui/src/unicode-categories.json from CPython's unicodedata.

The JS engine ports must agree byte-for-byte with the Python engine, whose
sweep depends on unicodedata.category(). This script freezes THIS interpreter's
Unicode database (the same one the server pins per spec section 7) into
range-compressed JSON:

    {"unidata_version": "15.1.0",
     "cats": ["Cc","Cf",...],                  # index -> category name
     "ranges": [[start, end, catIndex], ...]}  # inclusive codepoint ranges

Proofline precedent: generated tables are never hand-edited; regenerate when
upstream pins a new Unicode version.
"""
import json
import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src" / "unicode-categories.json"

# All 30 Unicode general categories, stable order.
CATS = ["Lu", "Ll", "Lt", "Lm", "Lo", "Mn", "Mc", "Me", "Nd", "Nl", "No",
        "Pc", "Pd", "Ps", "Pe", "Pi", "Pf", "Po", "Sm", "Sc", "Sk", "So",
        "Zs", "Zl", "Zp", "Cc", "Cf", "Cs", "Co", "Cn"]
IDX = {c: i for i, c in enumerate(CATS)}

MAX_CP = 0x10FFFF

def main() -> None:
    cats = [unicodedata.category(chr(cp)) for cp in range(MAX_CP + 1)]
    ranges: list[list[int]] = []
    start = 0
    cur = cats[0]
    for cp in range(1, MAX_CP + 1):
        c = cats[cp]
        if c != cur:
            ranges.append([start, cp - 1, IDX[cur]])
            start, cur = cp, c
    ranges.append([start, MAX_CP, IDX[cur]])

    payload = {
        "generator": "gen_unicode_tables.py (CPython "
                     f"{sys.version.split()[0]})",
        "unidata_version": unicodedata.unidata_version,
        "cats": CATS,
        "ranges": ranges,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, separators=(",", ":")),
                   encoding="utf-8")
    # Browser twin: same data as an ES module (no fetch/fs needed anywhere).
    OUT_JS = OUT.with_suffix(".js")
    OUT_JS.write_text(
        "// GENERATED by ui/tools/gen_unicode_tables.py -- do not edit.\n"
        f"// unidata {payload['unidata_version']}, {len(ranges)} ranges\n"
        "export default " + json.dumps(payload, separators=(",", ":")) + ";\n",
        encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes) and {OUT_JS.name} "
          f"({len(ranges)} ranges, unidata {payload['unidata_version']})")


if __name__ == "__main__":
    main()
